### ISSUE TITLE
Show navigation bar while scrolling

### ISSUE THREAD

**Issue by sshiwangi** [DhruviThakkar210/Community_website#11]
Currently the page while scrolling is looking like this 
![Screenshot 2023-04-14 120838](https://user-images.githubusercontent.com/77545230/231964040-0532c1f7-31c5-4972-a481-c02083a27bb5.png)

On scrolling, show the navigation bar so that it looks something like this.
![Screenshot 2023-04-14 121626](https://user-images.githubusercontent.com/77545230/231965101-98c24c87-92dd-426a-abec-78481613614a.png)

**Comment by nitin-pandita** [comment]
I would like to work on it !!

**Comment by sshiwangi** [comment]
> I would like to work on it !!

Yeah @nitin-pandita you can work on it.

**Comment by yashpatilofficial** [comment]
@nitin-pandita you still working on it? or should I proceed?

**Comment by rahulrana701** [comment]
hi @sshiwangi can you assign this issue to me , I can work on this...

**Comment by MOHDNEHALKHAN** [comment]
![Community](https://user-images.githubusercontent.com/125626654/236110234-dfbe7f32-0c97-4d57-9b4d-b1052bda2d05.png)
@sshiwangi Please see the above page , If you like it I can create PR

**Comment by yeshavyas27** [comment]
make a pr, if it's done

**Comment by MOHDNEHALKHAN** [comment]
@yeshavyas27  Ok I will Create a PR

**Comment by yeshavyas27** [comment]
Can you change the background colour of nav bar to be same as website background shade, right now the difference is visible in the black shades?

**Comment by MOHDNEHALKHAN** [comment]
@yeshavyas27  What is the color of background shade?

**Comment by yeshavyas27** [comment]
#222327

**Comment by MOHDNEHALKHAN** [comment]
So i have to close the previous PR

**Comment by yeshavyas27** [comment]
Make a PR again with changes

**Comment by MOHDNEHALKHAN** [comment]
Ok👍🏻 Will do within 1hour

**Comment by MOHDNEHALKHAN** [comment]
@yeshavyas27 Please Check my PR
