### ISSUE TITLE
Button Styling

### ISSUE THREAD

**Issue by rahulrana701** [DhruviThakkar210/Community_website#14]
currently the buttons on the home page are showing no hover state, it would be better for styling purpose if we add some hover state in it ..
<img width="935" alt="Screenshot 2023-04-18 005739" src="https://user-images.githubusercontent.com/123585591/232591515-43bcc69b-66b8-43e8-9cf8-8b141df8b255.png">
and cursor pointer property is also missing in it....

**Comment by rahulrana701** [comment]
hi @sshiwangi can you assign this issue to me , I would like to work on this issue.......

**Comment by rahulrana701** [comment]
hi @sshiwangi I have created a pr regarding this issue, you can check it out..https://github.com/DhruviThakkar210/Community_website/pull/15#issue-1675565239

**Comment by sshiwangi** [comment]
> hi @sshiwangi I have created a pr regarding this issue, you can check it out..[#15 (comment)](https://github.com/DhruviThakkar210/Community_website/pull/15#issue-1675565239)

sure

**Comment by yeshavyas27** [comment]
Issue resolved

**Comment by yeshavyas27** [comment]
@sshiwangi is the issue resolved?
