### ISSUE TITLE
Links and card Information on About page

### ISSUE THREAD

**Issue by harshchandwani** [DhruviThakkar210/Community_website#20]
1. There are no links added to the website
2. Cards has Lorem Ipsum included, change them according to the needful.

**Comment by harshchandwani** [comment]
Please assign me this issue

**Comment by yeshavyas27** [comment]
Sure! you can work on it harsh

**Comment by yeshavyas27** [comment]
The links on the home page are also to be updated, can you also do that too?
The About page links are all done now as I merged your pull request

**Comment by harshchandwani** [comment]
Busy with an internship exam, give me a week, and I will work on this.Thanks :)

**Comment by yeshavyas27** [comment]
I'll do it when I have free time, no worries
Good luck for that!!
