### ISSUE TITLE
Links not Added in Events and Members page and also no newsroom page created

### ISSUE THREAD

**Issue by roy2pushkar** [DhruviThakkar210/Community_website#26]
![Screenshot (492)](https://github.com/DhruviThakkar210/Community_website/assets/75408762/1fb3e8e5-826b-424f-85a3-dfc355168a59)

No links are added of socials , about us etc. I attached ss and circled that and it should be better if add about us of community members at place of dummy .

**Comment by roy2pushkar** [comment]
Hey Please assign this PR to me .

**Comment by Nishitbaria** [comment]
I am assigning this issue to @roy2pushkar

**Comment by roy2pushkar** [comment]
hey @Nishitbaria  this issue is already fixed and merged in PR  #28  so i think this issue should be removed from In Progress level .
