### ISSUE TITLE
Contact us form 

### ISSUE THREAD

**Issue by roy2pushkar** [DhruviThakkar210/Community_website#27]
![Screenshot (495)](https://github.com/DhruviThakkar210/Community_website/assets/75408762/7614caeb-3735-4ba7-8ddc-8871353e23f7)
In contact us there is no links added for of our website and its looks good if we remove our website and add contacts us form like name , mail etc .

and  In Women Tech Hub section socials media links are also not added .

**Comment by roy2pushkar** [comment]
Hey Please assign this PR to me .

**Comment by yeshavyas27** [comment]
you can work on this

**Comment by roy2pushkar** [comment]
Hey  @yeshavyas27  some issued are fixed here #28 please check and merged in main .

**Comment by roy2pushkar** [comment]
@Nishitbaria  hey this issue is already fixed  and merged in PR #28   and in  #33 so i think  this issue should be removed from In Progress level .
