### ISSUE TITLE
Color of the hyperlinks

### ISSUE THREAD

**Issue by Shalini469717** [DhruviThakkar210/Community_website#29]
![image](https://github.com/DhruviThakkar210/Community_website/assets/99305545/b3593b41-8f47-4dd5-90d9-7ef349bfcedb)
![image](https://github.com/DhruviThakkar210/Community_website/assets/99305545/d7a6ab85-ad2d-4232-9fd8-d6546e520a60)

The links are white in events page and blue in others. I think it will be better if the links are white on all the pages, it matches the theme too.

**Comment by Shalini469717** [comment]
Can I work on this issue?

**Comment by yeshavyas27** [comment]
Sure, assigning this issue to you

**Comment by Shalini469717** [comment]
#30
