### ISSUE TITLE
footer size

### ISSUE THREAD

**Issue by ompatil19** [DhruviThakkar210/Community_website#9]
the footer size is too big  can be fixed and bought to one line will look much better 

If interested in above changes please let me know will change and submit pull request

**Comment by sshiwangi** [comment]
@ompatil19 You can work on the issue but make sure you add ss of the changes you made while creating a pr.

**Comment by ompatil19** [comment]
works sure!

**Comment by rahulrana701** [comment]
hi @sshiwangi please assign me this issue , I would like to work on this issue
